### PR TITLE
Apply schema to orientdb 4

### PR DESCRIPTION
**Pull request by kirillvasilenko**
Added OModelMetaData. All schema changes go through this object. It is a subclass of ModelMetaDataImpl, so it can go anywhere where ModelMetaDataImpl is expected.

I have not integrated OModelMetaData around (to OEntityStore and so on). I will do that in the upcoming merge requests.

### CODE REVIEW

**Comment by laa** [comment]
Hi @kirillvasilenko thank you for description, otherwise I would be completely lost in those comments :-)

**Comment by kirillvasilenko** [comment]
Actually, there are no 62 commits. If you look at the diff page, there are not many changes.

I wondered why GitHub shows so many commits. It seems that the reason is that we merge the branch as a single commit. So the history is lost, and GitHub can not understand that 50 out of those 60 are already in the branch.

**Review by laa — APPROVED** [review]
Hi Kirill.
Cool, thank you :-)

**Comment by laa** [comment]
@kirillvasilenko BTW, I like the logging you use. That is very cool.

**Comment by kirillvasilenko** [comment]
@laa logging you mean in the schemaInitializer, that is "withPadding"?

**Pull request merged**
