### PR TITLE
String case sensitive search option

### PR DESCRIPTION
**Pull request by smallshen**

### CODE REVIEW

**Comment by smallshen** [comment]
Forget Java doesn't support kotlin default arguments.

**Comment by smallshen** [comment]
I have some commits that have not yet been pushed that change the original index behavior. 
Which one is better?
1. add a option in PersistentEntityStoreConfig eg. caseSensitive (default to false)
2. Create a separate tree for case sensitive of specific property of a type (require explicitly set, e.g store.enableCaseSensitive(String entityType, String propertyName))

**Comment by laa** [comment]
Hi @smallshen as you can see, the build is failing with your changes, could you fix the build first, then I will gladly review your fix.

**Comment by laa** [comment]
Closed because of no response.

**Pull request closed without merging**
