### PR TITLE
Delete links with indices

### PR DESCRIPTION
**Pull request by kirillvasilenko**
Fixed OVertexEntity.deleteLink() and Co, OVertexEntity.setLink() and Co. Added tests.

### CODE REVIEW

**Comment by andrii0lomakin** [comment]
@kirillvasilenko can you answer my questions?

**Comment by kirillvasilenko** [comment]
@andrii0lomakin, sure. As soon as you ask them :)

image

**Comment by andrii0lomakin** [comment]
image

**Comment by kirillvasilenko** [comment]
@andrii0lomakin, it seems distributed anomalies in action. I will answer you here as I do not have those questions on my side :)

 > How it is possible that the bag is null

Normally, it should not be possible. But if we delete an edge when the complementary property has already been created but has not been initialized, it is possible.

> Do not save the edge?

Yeah, I tried, the tests work. I kept this save() because of the "not save() phobia" I got while working with Orient. If you prefer me to remove that operator, no problem, only say.

**Comment by andrii0lomakin** [comment]
>Yeah, I tried, the tests work. I kept this save() because of the "not save() phobia" I got while working with Orient. If you prefer me >to remove that operator, no problem, only say.
I am afraid and can recreate record, please remove this line and I will merge PR

**Comment by kirillvasilenko** [comment]
@andrii0lomakin, you got it.

Now, additionally to the "not saved()" phobia, I have the  "saved() but may be recreated" phobia :((

**Review by andrii0lomakin — APPROVED** [review]

**Pull request merged**
