### PR TITLE
Revert "During the load entity is created in detached form and real r…

### PR DESCRIPTION
**Pull request by kirillvasilenko**

### CODE REVIEW

**Comment by andrii0lomakin** [comment]
Hi @kirillvasilenko please do not restore reload it is not needed the rest is OK.

**Comment by kirillvasilenko** [comment]
@andrii0lomakin ,  unfortunately, I do not understand what you mean. I reverted the whole commit. Do you want me to do some additional changes on top of that?

**Comment by kirillvasilenko** [comment]
Do you want me to remove all the `reload()` calls in the OVertexEntity?

**Comment by kirillvasilenko** [comment]
Do we need the reload() method at all?

**Comment by kirillvasilenko** [comment]
@andrii0lomakin , done. Including commenting out the execution plan printing.

**Comment by andrii0lomakin** [comment]
@kirillvasilenko tests are still failing; I can not merge in the main branch unstable code. Please check why

**Comment by kirillvasilenko** [comment]
@andrii0lomakin, done

**Review by andrii0lomakin — APPROVED** [review]

**Pull request merged**
